os: osx
osx_image: xcode11.5
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EANBarcodeGenerator.xcworkspace -scheme EANBarcodeGenerator-Example -sdk iphonesimulator13.5 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint